apiVersion: batch/v1
kind: CronJob
metadata:
  name: msynabot.rfc-protect
  labels:
    name: msynabot.rfc-protect
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "0 22 * * 5"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: rfc-protect
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            env:
            - name: HOME
              value: /data/project/msynabot
            - name: PYTHONPATH
              value: /data/project/shared/pywikibot/stable
            workingDir: /data/project/msynabot/pywikibot_tasks/rfc_protect
            command: [ venv/bin/python3 ]
            args: [ main.py ]
          restartPolicy: OnFailure
